### ISSUE TITLE
rdb tools

### ISSUE THREAD

**Issue by AliNiestani** [sripathikrishnan/redis-rdb-tools#107]
Does the rdb-tools handle this question?

https://stackoverflow.com/questions/47751591/how-to-transfer-some-redis-data-required-to-another-file

**Comment by oranagra** [comment]
the [protocol](https://github.com/sripathikrishnan/redis-rdb-tools#emitting-redis-protocol) command can be used to convert the rdb file to a list of commands, you can then dump that to a file, edit it (trimming what you don't want), and then netcat it into a redis listening port.

but i think that (assuming you wanna keep complete values, and not portions of them) you better use the [MIGRATE](https://redis.io/commands/migrate) command
