### ISSUE TITLE
Invalid RDB vesrion number 7

### ISSUE THREAD

**Issue by QuanGangDeng** [sripathikrishnan/redis-rdb-tools#115]
after I used rdb tools to analyze memoy, this Exception comes out 
I've seen the source code,but I don't know to deal with it.
 if version < 1 or version > 6 :
            raise Exception('verify_version', 'Invalid RDB version number %d' % version)

**Comment by oranagra** [comment]
@QuanGangDeng you're probably using an old version of rdb-tools, newer versions support up to rdb version 8 (of redis 4.0)

**Comment by QuanGangDeng** [comment]
@oranagra Thank you so much,It's working really well in the least version
