### ISSUE TITLE
When rdb-tools support object meta info dump?

### ISSUE THREAD

**Issue by linux2014linux** [sripathikrishnan/redis-rdb-tools#119]
Now, rdb-tools support key summary information dump to file. Sometime, I need look for the key meta info(idletime etc.). Do you have a plan that rdb-tools support dump key meta information?

**Comment by sripathikrishnan** [comment]
Unfortunately, the rdb dump file format does not contain meta-data such as idle time. The only meta-data available is the expiry, and that was added to the CSV recently in unstable.

Antirez has hinted that a newer version of RDB file will contain additional meta-data information about keys such as idle time / last access time. When that format is published, rdb tools will start supporting it.

**Comment by linux2014linux** [comment]
OK, thanks!
