### ISSUE TITLE
Unable to install rdb tools in mac os

### ISSUE THREAD

**Issue by keerthi310** [sripathikrishnan/redis-rdb-tools#126]
Reading https://pypi.python.org/simple/redis/
Download error on https://pypi.python.org/simple/redis/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!

**Comment by sripathikrishnan** [comment]
It's not clear what you are trying to do. Can you tell me what commands you are executing?

**Comment by koreindian** [comment]
I believe `pip install rdbtools`.
I am seeing a similar issue on OS X.

Collecting rdbtools
```
  Could not fetch URL https://pypi.python.org/simple/rdbtools/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
```

**Comment by graysonchen** [comment]
@koreindian 👍 
**Nevermind, this is because pip 9.0.1 is broken as of April.**

**Comment by sripathikrishnan** [comment]
Thanks for confirming!
