### ISSUE TITLE
Question: the correctness  of rdbtools.memprofiler#sizeof_string when input string isn't ascii

### ISSUE THREAD

**Issue by spccold** [sripathikrishnan/redis-rdb-tools#127]
~~~python
def sizeof_string(self, string):
        # https://github.com/antirez/redis/blob/unstable/src/sds.h
        try:
            num = int(string)
            if num < REDIS_SHARED_INTEGERS :
                return 0
            else :
                return 8
        except ValueError:
            pass
        l = len(string)
        if self._redis_version < StrictVersion('3.2'):
            return self.malloc_overhead(l + 8 + 1)
        if l < 2**5:
            return self.malloc_overhead(l + 1 + 1)
        if l < 2**8:
            return self.malloc_overhead(l + 1 + 2 + 1)
        if l < 2**16:
            return self.malloc_overhead(l + 1 + 4 + 1)
        if l < 2**32:
            return self.malloc_overhead(l + 1 + 8 + 1)
        return self.malloc_overhead(l + 1 + 16 + 1)
~~~

when the input string is chinese, like `你好`, len(string) return 2, but contains 6 bytes in fact

![image](https://user-images.githubusercontent.com/8461826/41328024-883a790e-6ef8-11e8-9c16-8f068bd23168.png)

I am not familiar with jemalloc memory allocation strategy, maybe bytes number is more correctly for memory calculation

**Comment by sripathikrishnan** [comment]
You are right that bytes is correct for memory calculation. 

I'm reasonably sure that the 'string' argument that's passed to a function is a python bytes object. So ultimately, it will return 6 bytes. The len function works for both strings and byte like objects.
