### ISSUE TITLE
Binary data output

### ISSUE THREAD

**Issue by venkates** [sripathikrishnan/redis-rdb-tools#21]
Hi, I store binary data as values for my keys. I see multiple bytes are combined into a single unicode character when I use rdb-tools to dump my data in json.

This is what I get when dumping from redis using redis-cli:

redis 127.0.0.1:6381> get "43542948993:Brown Home Improvement"
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01Y\xcc\x9c\x01"

This is what I get from the rdb-tools dump:
[{
"43542948993:Brown Home Improvement":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001Y\u031c\u0001"}]

The \xcc\x9c is being combined into \u031c. I am guessing the tools is reading the data as utf-8 and converting it to unicode. Is there a way to preserve the bytes?

**Comment by amotzg** [comment]
@venkates, long time but worthwhile to mention, even for future searches.  
With, recently merged, string escape option you can now override utf-8 decoding attempts. Using `--escape raw` will pass bytes as is, avoiding any decode attempt.  It will still be `\uXXXX` escaped but with raw values.

@oranagra this can be closed now having an optional solution.
