### ISSUE TITLE
Invalid json format by missing comma when handling hash

### ISSUE THREAD

**Issue by labelnolongerexists** [sripathikrishnan/redis-rdb-tools#22]
When hash's size is greater then 253, comma will be lost in the output json file.

Here's an example data. Copy it to a formatter and check it out.

{"2012-12-26 03:45":"139#0#117#1.0","2012-12-26 12:55":"461#0#383#1.0","2012-12-26 22:50":"244#0#214#1.0","2012-12-26 23:10":"205#0#186#1.0","2012-12-26 14:00":"424#0#357#1.0","2012-12-26 00:55":"195#0#139#1.0","2012-12-26 10:50":"354#0#290#1.0","2012-12-26 09:25":"301#0#261#1.0","2012-12-26 15:45":"428#0#378#1.0","2012-12-26 20:20":"345#0#285#1.0","2012-12-26 07:20":"210#0#181#1.0","2012-12-26 02:00":"184#0#156#1.0","2012-12-26 13:15":"423#0#345#1.0","2012-12-26 01:15":"199#0#158#1.0","2012-12-26 22:25":"294#0#241#1.0","2012-12-26 04:05":"145#0#124#1.0","2012-12-26 16:30":"452#0#369#1.0","2012-12-26 06:35":"180#0#146#1.0","2012-12-26 01:40":"160#0#145#1.0","2012-12-26 10:25":"318#0#270#1.0","2012-12-26 16:05":"420#0#358#1.0","2012-12-26 04:30":"153#0#125#1.0","2012-12-26 18:35":"444#0#354#1.0","2012-12-26 09:50":"326#0#283#1.0","2012-12-26 13:40":"415#0#351#1.0","2012-12-26 11:10":"377#0#304#1.0","2012-12-26 19:20":"412#0#326#1.0","2012-12-26 20:45":"355#0#299#1.0","2012-12-26 15:10":"398#0#330#1.0","2012-12-26 07:45":"229#0#192#1.0","2012-12-26 05:15":"163#0#136#1.0","2012-12-26 21:30":"351#0#279#1.0","2012-12-26 02:50":"154#0#130#1.0","2012-12-26 08:05":"288#0#226#1.0","2012-12-26 02:25":"156#0#141#1.0","2012-12-26 08:30":"229#0#194#1.0","2012-12-26 06:00":"169#0#129#1.0","2012-12-26 14:25":"480#0#390#1.0","2012-12-26 23:35":"173#0#152#1.0","2012-12-26 18:00":"442#0#362#1.0","2012-12-26 16:55":"467#0#365#1.0","2012-12-26 04:55":"165#0#137#1.0","2012-12-26 03:10":"176#0#140#1.0","2012-12-26 00:20":"178#0#156#1.0","2012-12-26 19:45":"411#0#344#1.0","2012-12-26 21:05":"370#0#314#1.0","2012-12-26 17:40":"418#0#344#1.0","2012-12-26 05:40":"172#0#140#1.0","2012-12-26 12:20":"416#0#344#1.0","2012-12-26 17:15":"446#0#377#1.0","2012-12-26 11:35":"397#0#337#1.0","2012-12-26 14:50":"446#0#355#1.0","2012-12-26 06:50":"173#0#142#1.0","2012-12-26 23:00":"230#0#194#1.0","2012-12-26 01:05":"175#0#152#1.0","2012-12-26 18:50":"391#0#322#1.0","2012-12-26 07:10":"196#0#170#1.0","2012-12-26 22:15":"300#0#240#1.0","2012-12-26 09:40":"327#0#280#1.0","2012-12-26 03:35":"184#0#133#1.0","2012-12-26 13:05":"445#0#340#1.0","2012-12-26 20:10":"404#0#326#1.0","2012-12-26 12:45":"397#0#327#1.0","2012-12-26 19:10":"424#0#345#1.0","2012-12-26 06:25":"183#0#152#1.0","2012-12-26 13:30":"454#0#384#1.0","2012-12-26 00:45":"181#0#155#1.0","2012-12-26 21:55":"291#0#247#1.0","2012-12-26 04:20":"131#0#111#1.0","2012-12-26 10:40":"361#0#299#1.0","2012-12-26 18:25":"406#0#350#1.0","2012-12-26 01:30":"175#0#143#1.0","2012-12-26 09:15":"319#0#266#1.0","2012-12-26 08:55":"298#0#255#1.0","2012-12-26 15:35":"428#0#356#1.0","2012-12-26 11:00":"345#0#287#1.0","2012-12-26 10:15":"367#0#291#1.0","2012-12-26 22:40":"285#0#236#1.0","2012-12-26 16:20":"427#0#358#1.0","2012-12-26 05:30":"126#0#111#1.0","2012-12-26 23:50":"231#0#200#1.0","2012-12-26 16:45":"529#0#419#1.0","2012-12-26 11:50":"436#0#358#1.0","2012-12-26 23:25":"226#0#183#1.0","2012-12-26 19:35":"455#0#372#1.0","2012-12-26 07:35":"202#0#178#1.0","2012-12-26 03:00":"173#0#142#1.0","2012-12-26 12:10":"372#0#299#1.0","2012-12-26 08:20":"216#0#189#1.0","2012-12-26 14:15":"430#0#360#1.0","2012-12-26 05:05":"141#0#121#1.0","2012-12-26 00:10":"196#0#157#1.0","2012-12-26 20:35":"382#0#304#1.0","2012-12-26 21:20":"373#0#289#1.0","2012-12-26 17:30":"397#0#347#1.0","2012-12-26 14:40":"463#0#375#1.0","2012-12-26 02:15":"177#0#146#1.0","2012-12-26 04:45":"112#0#102#1.0","2012-12-26 02:40":"157#0#138#1.0","2012-12-26 11:25":"447#0#344#1.0","2012-12-26 17:05":"425#0#348#1.0","2012-12-26 13:55":"449#0#375#1.0","2012-12-26 01:55":"186#0#157#1.0","2012-12-26 15:00":"463#0#376#1.0","2012-12-26 17:55":"410#0#340#1.0","2012-12-26 06:15":"146#0#126#1.0","2012-12-26 19:00":"402#0#329#1.0","2012-12-26 09:05":"315#0#262#1.0","2012-12-26 15:25":"432#0#367#1.0","2012-12-26 13:20":"455#0#366#1.0","2012-12-26 18:15":"478#0#387#1.0","2012-12-26 09:30":"318#0#274#1.0","2012-12-26 07:00":"190#0#169#1.0","2012-12-26 15:50":"457#0#380#1.0","2012-12-26 08:45":"264#0#216#1.0","2012-12-26 16:10":"418#0#357#1.0","2012-12-26 10:30":"326#0#265#1.0","2012-12-26 03:25":"129#0#114#1.0","2012-12-26 22:30":"296#0#238#1.0","2012-12-26 20:00":"377#0#316#1.0","2012-12-26 06:40":"177#0#156#1.0","2012-12-26 18:40":"418#0#351#1.0","2012-12-26 00:35":"196#0#157#1.0","2012-12-26 21:45":"324#0#258#1.0","2012-12-26 03:50":"121#0#104#1.0","2012-12-26 04:10":"119#0#106#1.0","2012-12-26 22:05":"308#0#242#1.0","2012-12-26 10:05":"310#0#261#1.0","2012-12-26 12:35":"383#0#320#1.0","2012-12-26 01:20":"171#0#156#1.0","2012-12-26 05:55":"179#0#146#1.0","2012-12-26 05:20":"150#0#126#1.0","2012-12-26 02:30":"184#0#155#1.0","2012-12-26 08:10":"265#0#223#1.0","2012-12-26 14:30":"469#0#369#1.0","2012-12-26 17:20":"473#0#390#1.0","2012-12-26 04:35":"118#0#103#1.0","2012-12-26 09:55":"332#0#285#1.0","2012-12-26 20:50":"336#0#269#1.0","2012-12-26 19:50":"366#0#310#1.0","2012-12-26 19:25":"421#0#352#1.0","2012-12-26 21:10":"330#0#278#1.0","2012-12-26 02:05":"177#0#143#1.0","2012-12-26 13:45":"457#0#351#1.0","2012-12-26 11:40":"414#0#324#1.0","2012-12-26 23:15":"220#0#191#1.0","2012-12-26 07:25":"214#0#184#1.0","2012-12-26 00:00":"177#0#143#1.0","2012-12-26 23:40":"178#0#166#1.0","2012-12-26 20:25":"367#0#304#1.0","2012-12-26 11:15":"402#0#328#1.0","2012-12-26 01:45":"157#0#131#1.0","2012-12-26 16:35":"431#0#364#1.0","2012-12-26 12:00":"405#0#340#1.0","2012-12-26 22:55":"203#0#182#1.0","2012-12-26 10:55":"402#0#321#1.0","2012-12-26 14:05":"386#0#330#1.0","2012-12-26 07:50":"233#0#194#1.0","2012-12-26 00:50":"227#0#171#1.0","2012-12-26 06:05":"163#0#138#1.0","2012-12-26 22:20":"275#0#225#1.0","2012-12-26 12:50":"400#0#340#1.0","2012-12-26 17:45":"439#0#358#1.0","2012-12-26 16:00":"450#0#368#1.0","2012-12-26 18:30":"415#0#351#1.0","2012-12-26 06:30":"181#0#148#1.0","2012-12-26 10:20":"376#0#308#1.0","2012-12-26 12:25":"373#0#324#1.0","2012-12-26 13:10":"433#0#357#1.0","2012-12-26 03:15":"140#0#125#1.0","2012-12-26 21:35":"372#0#289#1.0","2012-12-26 00:25":"208#0#166#1.0","2012-12-26 15:15":"485#0#385#1.0","2012-12-26 05:45":"144#0#128#1.0","2012-12-26 03:40":"146#0#122#1.0","2012-12-26 08:35":"264#0#228#1.0","2012-12-26 01:10":"203#0#177#1.0","2012-12-26 14:55":"467#0#376#1.0","2012-12-26 04:00":"123#0#103#1.0","2012-12-26 09:20":"309#0#254#1.0","2012-12-26 18:05":"437#0#352#1.0","2012-12-26 02:55":"134#0#118#1.0","2012-12-26 15:40":"412#0#363#1.0","2012-12-26 21:00":"352#0#305#1.0","2012-12-26 16:25":"439#0#343#1.0","2012-12-26 14:20":"451#0#373#1.0","2012-12-26 07:15":"196#0#166#1.0","2012-12-26 11:05":"355#0#304#1.0","2012-12-26 16:50":"425#0#350#1.0","2012-12-26 07:40":"214#0#186#1.0","2012-12-26 10:45":"371#0#301#1.0","2012-12-26 22:45":"229#0#194#1.0","2012-12-26 18:55":"448#0#352#1.0","2012-12-26 17:10":"452#0#384#1.0","2012-12-26 06:55":"200#0#168#1.0","2012-12-26 20:40":"351#0#294#1.0","2012-12-26 20:15":"390#0#323#1.0","2012-12-26 11:30":"387#0#324#1.0","2012-12-26 02:20":"166#0#143#1.0","2012-12-26 23:30":"227#0#193#1.0","2012-12-26 08:00":"184#0#167#1.0","2012-12-26 09:45":"312#0#264#1.0","2012-12-26 04:25":"139#0#124#1.0","2012-12-26 19:40":"384#0#320#1.0","2012-12-26 04:50":"145#0#112#1.0","2012-12-26 23:05":"227#0#198#1.0","2012-12-26 05:10":"122#0#108#1.0","2012-12-26 13:35":"460#0#380#1.0","2012-12-26 19:15":"409#0#337#1.0","2012-12-26 01:35":"185#0#158#1.0","2012-12-26 14:45":"420#0#354#1.0","2012-12-26 05:35":"156#0#127#1.0","2012-12-26 09:10":"287#0#236#1.0","2012-12-26 08:50":"269#0#219#1.0","2012-12-26 08:25":"225#0#179#1.0","2012-12-26 21:50":"310#0#258#1.0","2012-12-26 01:00":"207#0#175#1.0","2012-12-26 15:30":"427#0#365#1.0","2012-12-26 22:10":"292#0#243#1.0","2012-12-26 03:30":"160#0#109#1.0","2012-12-26 11:55":"410#0#327#1.0","2012-12-26 02:45":"171#0#148#1.0","2012-12-26 18:20":"445#0#353#1.0","2012-12-26 12:15":"397#0#329#1.0","2012-12-26 17:35":"464#0#368#1.0","2012-12-26 13:00":"435#0#365#1.0","2012-12-26 00:15":"167#0#146#1.0","2012-12-26 12:40":"394#0#318#1.0","2012-12-26 00:40":"188#0#156#1.0","2012-12-26 06:20":"192#0#155#1.0","2012-12-26 03:05":"143#0#125#1.0","2012-12-26 10:10":"374#0#298#1.0","2012-12-26 21:25":"376#0#297#1.0","2012-12-26 15:05":"471#0#391#1.0","2012-12-26 16:15":"423#0#344#1.0","2012-12-26 05:00":"142#0#117#1.0","2012-12-26 22:35":"254#0#216#1.0","2012-12-26 07:05":"180#0#148#1.0","2012-12-26 07:30":"212#0#176#1.0","2012-12-26 17:00":"453#0#369#1.0","2012-12-26 01:25":"159#0#143#1.0","2012-12-26 06:45":"176#0#142#1.0","2012-12-26 01:50":"162#0#137#1.0","2012-12-26 13:50":"431#0#361#1.0","2012-12-26 16:40":"460#0#384#1.0","2012-12-26 13:25":"443#0#361#1.0","2012-12-26 03:55":"152#0#117#1.0","2012-12-26 02:10":"193#0#155#1.0","2012-12-26 19:05":"395#0#335#1.0","2012-12-26 15:55":"466#0#381#1.0","2012-12-26 18:45":"391#0#317#1.0","2012-12-26 23:20":"220#0#197#1.0","2012-12-26 04:40":"120#0#103#1.0","2012-12-26 04:15":"135#0#120#1.0""2012-12-26 20:05":"383#0#337#1.0""2012-12-26 10:35":"360#0#296#1.0""2012-12-26 11:20":"424#0#323#1.0""2012-12-26 09:35":"277#0#234#1.0""2012-12-26 19:30":"336#0#288#1.0""2012-12-26 20:30":"383#0#304#1.0""2012-12-26 14:10":"417#0#356#1.0""2012-12-26 22:00":"285#0#247#1.0""2012-12-26 03:20":"148#0#116#1.0""2012-12-26 00:30":"177#0#149#1.0""2012-12-26 05:50":"167#0#134#1.0""2012-12-26 12:30":"401#0#324#1.0""2012-12-26 14:35":"438#0#372#1.0""2012-12-26 10:00":"315#0#269#1.0""2012-12-26 17:50":"552#0#418#1.0""2012-12-26 23:45":"192#0#161#1.0""2012-12-26 12:05":"365#0#311#1.0""2012-12-26 21:40":"320#0#257#1.0""2012-12-26 18:10":"434#0#350#1.0""2012-12-26 02:35":"151#0#142#1.0""2012-12-26 05:25":"136#0#123#1.0""2012-12-26 07:55":"254#0#189#1.0""2012-12-26 19:55":"381#0#329#1.0""2012-12-26 21:15":"353#0#284#1.0""2012-12-26 00:05":"169#0#137#1.0""2012-12-26 08:15":"225#0#190#1.0""2012-12-26 08:40":"268#0#236#1.0""2012-12-26 17:25":"450#0#364#1.0""2012-12-26 09:00":"320#0#256#1.0""2012-12-26 20:55":"339#0#278#1.0""2012-12-26 15:20":"479#0#401#1.0""2012-12-26 06:10":"182#0#149#1.0""2012-12-26 11:45":"394#0#323#1.0"}

**Comment by oranagra** [comment]
i think the issue is already resolved, tested on a hash with 500 items and it seems to work fine.
please let me know if you think otherwise.
