### ISSUE TITLE
Need Support for Python 3.3

### ISSUE THREAD

**Issue by YuePan** [sripathikrishnan/redis-rdb-tools#41]
Here's the error message:

$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from rdbtools import __version__
  File "c:\Users\yupan\code\redis-rdb-tools\rdbtools\__init__.py", line 2, in <m
odule>
    from rdbtools.callbacks import JSONCallback, DiffCallback, ProtocolCallback
  File "c:\Users\yupan\code\redis-rdb-tools\rdbtools\callbacks.py", line 8
    ESCAPE = re.compile(ur'[\x00-\x1f\\"\b\f\n\r\t\u2028\u2029]')
                                                               ^
SyntaxError: invalid syntax

**Comment by joshowen** [comment]
Is there any plan for python3 support?

**Comment by oranagra** [comment]
@joshowen i don't have any plans currently, but i'll gladly accept pull requests.
@mihu i noticed you have a python3 branch in your repo, can you tell us what's the status there? i.e. how complete it is, and what's left to do?

**Comment by mihu** [comment]
I think it's not complete yet. There were some failing corner tests. But most of the stuff in the branch is needed for python3 support anyway. I can try to finish it and prepare PR or you can just cherry-pick the commits you think are sane.

**Comment by oranagra** [comment]
@mihu if you can, please try to finish and make a PR based on the current master branch.

i imagine the current master branch has some changes not in your branch, and also your branch may have things that didn't make it yet into the master, so depending on the extent of the changes needed it might require some work.

even if that's not 100% complete, as long as it doesn't add any regression on python 2.x we can merge it as it is a step forward.

thanks.

**Comment by mihu** [comment]
@oranagra there you have it #73

**Comment by oranagra** [comment]
@joshowen @YuePan python 3 support was added by @mihu and now merged to the master branch, please test it if you can.
