### ISSUE TITLE
redis-memory-for-key installation issues

### ISSUE THREAD

**Issue by alonisser** [sripathikrishnan/redis-rdb-tools#51]
Running redis-memory-for-key fails unless I independently install a "global" redis python lib:

> > pip install redis

I noticed the setup.py is missing a:

``` python
install_requires=[
        "redis",

    ],
```

So I guess this is the issue. I can send a PR that solves this, if this is acceptable by you.

Also: Thanks for this great tool! saved me this week

**Comment by vesper8** [comment]
Thank you, I was having the same issue and installing redis via pip fixed it.

**Comment by amotzg** [comment]
@oranagra could this have been solved by 9f521469acaa1776c6df61f8c12c9556cce8065b ?

**Comment by oranagra** [comment]
Yes, fixed already, thank you.
