### ISSUE TITLE
Import of RDB file to redis-cli pipe fails

### ISSUE THREAD

**Issue by Crispy1975** [sripathikrishnan/redis-rdb-tools#61]
Hi, while I can see this project hasn't been worked on for a while I thought it might be useful to document an issue we came across today while importing an RDB file from a read replica we run into a fresh AWS ElastiCache cluster.

```
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.6', 'console_scripts', 'rdb')()
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 306, in parse
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 369, in read_object
    self._callback.rpush(self._key, val)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 340, in rpush
    self.emit('RPUSH', key, value)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 298, in emit
    self._out.write(u"$" + unicode(len(unicode(arg))) + u"\r\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4614: ordinal not in range(128)
All data transferred. Waiting for the last reply...
ERR Protocol error: expected '$', got ' '
```

If this is a simple fix or something we are doing wrong would love to know. We installed using `pip` and the command we ran was `rdb --command protocol ~/redisprod-2015-08-27-100001.rdb | redis-cli -h xxxxxxx.xxxxxx.xx.xxxx.xxxx.cache.amazonaws.com --pipe`.

Running the same command with out piping into `redis-cli` produces the following error:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4614: ordinal not in range(128)
```

**Comment by wdalmut** [comment]
:+1:

**Comment by ryangraham** [comment]
I ran into the exact same error today. I was also piping to elasticache. This guy's fork fixed it for me.

`sudo pip install git+https://github.com/lesandr/redis-rdb-tools@1f7bcf366073adf5510ad18f1efe0bf46ae5e0c1 --upgrade`

I had to specify a commit in order to load more than one database. Something important was commented out in the next commit.

**Comment by siawyoung** [comment]
I also faced the same problem with the UnicodeDecodeError and can confirm that the above fork works. Thanks a lot! @ryangraham

**Comment by oranagra** [comment]
fixed by #77

**Comment by shalavadiharish** [comment]
@Crispy1975 ,

but when i try i get below error 
root@myhost:/home/ubuntu# rdb --command protocol /home/ubuntu/dumptest.rdb

Command 'rdb' not found, but there are 22 similar ones.

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
