### ISSUE TITLE
Support Redis 3.x

### ISSUE THREAD

**Issue by anthonator** [sripathikrishnan/redis-rdb-tools#67]
Getting the following error when using Redis 3.2

```
Traceback (most recent call last):
  File "/usr/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.6', 'console_scripts', 'rdb')()
  File "/usr/lib/python2.7/site-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 274, in parse
    self.verify_version(f.read(4))
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 612, in verify_version
    raise Exception('verify_version', 'Invalid RDB version number %d' % version)
Exception: ('verify_version', 'Invalid RDB version number 7')
```

with the dump file

```
REDIS0007�	redis-ver3.2.0�
redis-bits�@�ctime�d�2W�used-mem�ؔ��helloworld��w9�=Z��
```

**Comment by shaneog** [comment]
Since this repository doesn't seem to be maintained, is there a fork somewhere that can deal with RDB v7?

**Comment by mihu** [comment]
it's not perfect, but it works for my usecase https://github.com/mihu/redis-rdb-tools

**Comment by shaneog** [comment]
@mihu Great. You should open a PR to this repo.

**Comment by mihu** [comment]
What for? This repo is apparently unmaintained.

**Comment by shaneog** [comment]
@mihu Agreed. However, this still remains the _primary_ repo for this tool. When people come here with issues they check the PR list to see if their issue has been fixed by someone else. 
Opening a PR for RDB v7/Redis 3.x support will help others.

Furthermore, if [another committer takes over maintenance](https://github.com/sripathikrishnan/redis-rdb-tools/issues/58), having the PR open will help to quickly get this tool in good shape again.

**Comment by mihu** [comment]
I think anyone willing to dig a little will find this issue as I did.

**Comment by mihu** [comment]
Merged most of the PRs to https://github.com/mihu/redis-rdb-tools

**Comment by oranagra** [comment]
redis 3.2 RDB v7 added with commit https://github.com/sripathikrishnan/redis-rdb-tools/commit/8ba5e9b68daf9517e1058c21cf866b12ba126f6e

@mihu FYI, i looked at the quicklist parsing in your fork and it seems to put the ziplists as list elements rather than unzipping them.
