### ISSUE TITLE
big rdb

### ISSUE THREAD

**Issue by scu2013** [sripathikrishnan/redis-rdb-tools#76]
Hi, Now I have a huge rdb file which is about 50G. I cost so much time to analyze memory by using this tool. Any advise?

**Comment by oranagra** [comment]
Python is slow, you can try another (faster) python interpreter such as PyPy.

**Comment by Gauravshah** [comment]
Did try pypy and the processing time came down from 12 hours to 4.4 hours. In case somebody else at the same thing.
