### ISSUE TITLE
TypeError: sequence item 1: expected a bytes-like object, str found

### ISSUE THREAD

**Issue by shivam-maharshi** [sripathikrishnan/redis-rdb-tools#79]
**Command: c:\Python34\Scripts>rdb --command json C:/Users/Sam/Downloads/dump.rdb**
**OS: Windows 10**
**Python Version: 3.4**

`c:\Python34\Scripts>rdb --command json C:/Users/Sam/Downloads/dump.rdb
[{
Traceback (most recent call last):
  File "c:\Python34\Scripts\rdb-script.py", line 11, in <module>
    load_entry_point('rdbtools==0.1.7', 'console_scripts', 'rdb')()
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\cli\rdb.py", line 79, in main
    parser.parse(dump_file)
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\parser.py", line 304, in parse
    self.parse_fd(open(filename, "rb"))
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\parser.py", line 357, in parse_fd
    self.read_object(f, data_type)
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\parser.py", line 425, in read_object
    self._callback.set(self._key, val, self._expiry, info={'encoding':'string'})
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\callbacks.py", line 151, in set
    self._out.write('%s:%s' % (encode_key(key), encode_value(value)))
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\callbacks.py", line 102, in encode_value
    return _encode(s, quote_numbers=False)
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\callbacks.py", line 96, in _encode
    return _encode_basestring_ascii(s)
  File "C:\Python34\lib\site-packages\rdbtools-0.1.7-py3.4.egg\rdbtools\callbacks.py", line 77, in _encode_basestring_ascii
    return '"' + str(ESCAPE_ASCII.sub(replace, s)) + '"'
TypeError: sequence item 1: expected a bytes-like object, str found`

Can someone please take a look at this and tell me what the issue is? Any help is appreciated. Thanks!

**Comment by amotzg** [comment]
The key/value encoding methods in callbacks.py do some 'best effort' to read utf-8 and to escape for JSON ASCII strings. With Python 3, values passed from the RdbParser come in a _bytes_ like type. ASCII escaping code does not take this into account and try to combine escape sequence as a _str_, but the [re module](https://docs.python.org/3.5/library/re.html) requires that:

>  the replacement string must be of the same type as both the pattern and the search string.

This can be solved with some hacking on __encode_basestring_ascii()_ to detect string types.
Though there are few more issues with this encoding code, like #21. And I would recommend solving this as part of a general design that also deal with other data type issues. On #78 I've offered one approach to this.

**Comment by shivam-maharshi** [comment]
@amotzg Thanks for replying. Both of these issues ( #21 & #78 ) are open. Do you or anyone else have a quick fix on GitHub somewhere? Any help will be appreciated. Thanks again!

**Comment by amotzg** [comment]
Nope, sorry. Only partial work on #78.
I'll try to commit something specific to my fork during the weekend, hope it'll workout...

**Comment by amotzg** [comment]
amotzg@ceb8d08fa5f2f6941d5ae8508b6741cb0f190618 should solve this issue. It is not quality fit to merge here, but tested to work with the expected JSON command cases. For both py2.7 and py3.5.

**Comment by shivam-maharshi** [comment]
@amotzg will try and let you know. Thanks!

**Comment by amotzg** [comment]
@shivam-maharshi any news testing with the hack?
I've pushed a more general solution to branch [amotzg/redis-rdb-tools/string_escape](https://github.com/amotzg/redis-rdb-tools/tree/string_escape). It is not thoroughly tested yet, but I believe it is more stable than original code using Python 3.4.
With the new method, JSON command will try to decode UTF-8 strings by default, but the _--escape_ switch can be used to pass raw data or base64 encode. Also, even when decoding UTF-8, it will not fail on illegal bytes, but escape them.

**Comment by shivam-maharshi** [comment]
@amotzg Unfortunately my setup crashed so I am setting it back up, I don't have bandwidth to test this now. I will let you know when I have some bandwidth.

**Comment by amotzg** [comment]
@shivam-maharsh fork branch is deleted after merge to here. You can use the master now to install from source.
Note, the project README.md is also updated to explain how parsing to JSON and escaping works.

@oranagra , I think this issue can be closed now.

**Comment by oranagra** [comment]
thanks.

**Comment by shivam-maharshi** [comment]
@amotzg Thanks for the update. This really helps. Will try and let you know :)
