### ISSUE TITLE
Regression from 0.1.8 to 0.1.9

### ISSUE THREAD

**Issue by miketheman** [sripathikrishnan/redis-rdb-tools#86]
Hi there!

Was trying to dump a file to json and it failed with this traceback, using 0.1.9:

```
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/rdbtools/cli/rdb.py", line 86, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 326, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 379, in parse_fd
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 479, in read_object
    self._callback.zadd(self._key, score, val)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/callbacks.py", line 112, in zadd
    self._out.write(self.encode_key(member) + b':' + self.encode_value(score))
  File "/usr/local/lib/python2.7/site-packages/rdbtools/callbacks.py", line 27, in encode_value
    val = encodehelpers.bytes_to_unicode(val, self._escape)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/encodehelpers.py", line 110, in bytes_to_unicode
    assert (isinstance(byte_data, type(b'')))
AssertionError
```

Downgraded to 0.1.8 and was able to complete the export to JSON.

Looks like it failed when it hit an object with ~200 key,value pairs, looking something like this:

```json
"terms.score": {
    "word": 2.0,
    "foo": 1.0,
    "bar": 0.0
}
```

I _think_ this was previously created as a ZSET, but I'm not certain.

**Comment by amotzg** [comment]
@miketheman thanks for the input!
I was able to reproduce this error using a ZSET and scores with fractional part, the above fix is tested to solve it. Also added a general test on callbacks to try and prevent this kind of errors in the future.
Please reopen or report another issue in case this still doesn't solve your issue.

**Comment by miketheman** [comment]
@amotzg Thanks for the patch.
I just tested 0.1.10 against the same dump file, and can see that the output as shown before now converts the json number datatype to strings:

Previously:

```json
"terms.score": {
    "word": 2.0,
    "foo": 1.0,
    "bar": 0.0
}
```

Now:

```json
"terms.score": {
    "word": "2.0",
    "foo": "1.0",
    "bar": "0.0"
}
```

In the `protocol` output, I can confirm that this is also being input as a string datatype, as denoted by `$3` before the score value.

**Comment by amotzg** [comment]
@miketheman this behavior with JSON numbers is built in to the new way we treat text encodings and JSON escaping. I'll open an issue for it, but I'm not sure when I'll get to handle it. Of course, you can also PR with a fix.
About the Redis protocol, by definition client commands should be an array of bulk strings. Numbers will always be sent as strings.
