### ISSUE TITLE
Pull #83 cause tests to fail on Python3.x

### ISSUE THREAD

**Issue by amotzg** [sripathikrishnan/redis-rdb-tools#90]
As part of adding `ntohu64` to `parser.py`, the way byte order is fixed was changed.
Instead of a simple series of shifts into a new value, the code now create an array object and convert it to string after flipping the bytes.
This cause a `TypeError` on Python3.x when calling `struct.unpack()` which expect a byte-like.

To fix this the array should be converted to bytes instead string, or use the previous way of flipping the values, or any other way that return a byte-like to `struct.unpack()`.

This problem is released in v0.1.9.

**Comment by oranagra** [comment]
thanks. fixed by #93
